### ISSUE TITLE
How to use header.

### ISSUE THREAD

**Issue by arasu01** [akashraje/BidirectionalCollectionViewLayout#1]
Can you please explain how to use the fixed header with this layout please,

**Comment by akashrcuelogic** [comment]
Are you referring to floating headers ? I'll push an update for floating header.

**Comment by akashraje** [comment]
Are you referring to floating headers ? I'll push an update for floating headers. We had to implement something similar.

**Comment by arasu01** [comment]
@akashraje yes i am referring the same.

**Comment by akashraje** [comment]
@arasu01 have a look at c5a12d7 commit.
