### ISSUE TITLE
Compiler warning when building with Xcode 7.3.1

### ISSUE THREAD

**Issue by DerekK19** [akashraje/BidirectionalCollectionViewLayout#3]
The file BidirectionCollectionLayout.m gives a compiler warning when built with Xcode 7.3.1:

<project path>/BidirectionCollectionLayout.m:227:12: Variable 'maxEdgeInsets' may be uninitialized when used here

I recommend changing the variable declaration so it initialises with zero offsets. This clears the compiler warning:

```
UIEdgeInsets maxEdgeInsets = UIEdgeInsetsZero;
```

**Comment by akashraje** [comment]
Thanks ! initialised the Insets.
